### ISSUE TITLE
Not producing PDF or legal tex

### ISSUE THREAD

**Issue by networks1** [ContextLab/abstract2paper#1]
Hi. First, thanks for putting this out.  Second, I'm wondering if I'm missing something. Step 7 is supposed to produce a pdf, but it doesn't (unless I'm not looking in the right place, I have no experience with colab).  If I copy the output to a file it is not recognized as legal tex or latex2e by TexWord on windows or by pdflatex on linux.  How can I get this rendered to a pdf?

**Comment by jeremymanning** [comment]
Hi @networks1, in the [latest release](https://github.com/ContextLab/abstract2paper/releases/tag/v0.2) I've added a file download dialog box.  If you run the [new colaboratory notebook](https://github.com/ContextLab/abstract2paper/blob/main/resources/abstract2paper_colaboratory.ipynb), it should prompt you at the end to download the .pdf and .tex files.
